# Generated by Django 5.1.6 on 2025-02-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.TextField()),
                ('review', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Default Author', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='films.film'),
            preserve_default=False,
        ),
    ]
