# Generated by Django 5.1.6 on 2025-02-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_rename_review_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
